name: repo-check
on: [push]
jobs:
  check-imports:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: snok/install-poetry@v1.3.4
        with:
          version: 1.8.0
          virtualenvs-create: true
          virtualenvs-in-project: false
          installer-parallel: true
      - run: poetry install
      - run: poetry run python python_tools/main.py
